### ISSUE TITLE
Additional tests

### ISSUE THREAD

**Issue by adore2005** [rnwzd/FSPBT-Image-Translation#3]
Hello, I have successfully tested the model and output the files in the "output" folder. If I want to test with some of my pictures, can I put some of my pictures in the "target" folder and run "eval. Py"? Or what kind of operation is needed?

**Comment by rnwzd** [comment]
To test the current model on some other photos, you have to put your pictures in the "input" folder named according to the right convention (%05d.png i.e. 00001.png) and then run eval.py.
However, the model may not give good results as it is a very small model trained on just two photos. It does not generalize well.

To train the same model with some different photo-drawing pairs you have to place photos in the input folder and matching drawings with matching filenames in the target folder.

Please refer to the original project for more insights [https://ondrejtexler.github.io/patch-based_training/](url)

**Comment by adore2005** [comment]
> 要在其他一些照片上测试当前模型，您必须将图片放在根据正确约定命名的“输入”文件夹中（%05d.png 即 00001.png），然后运行 ​​eval.py。
> 但是，该模型可能不会给出好的结果，因为它是一个仅在两张照片上训练的非常小的模型。它不能很好地概括。
> 
> 要使用一些不同的照片绘图对训练相同的模型，您必须将照片放在输入文件夹中，并在目标文件夹中使用匹配的文件名匹配绘图。
> 
> 更多见解请参考原项目[https://ondrejtexler.github.io/patch-based_training/](url)

I'd like to ask whether this model changes color photos into black and white? Can it turn several static expression pictures into coherent animation? Just like "https://github.com/OndrejTexler/Few-Shot-Patch-Based-Training"?Thank you for your answers.

**Comment by rnwzd** [comment]
It makes them black and white just because the target drawings are so. it should work the same as the original code if provided with the same data.
However, to make my code work you have to understand how the original project works, so I may suggest you start looking at that first, as it is more complete.

**Comment by adore2005** [comment]
> 它使它们变得黑白分明，因为目标图纸是如此。如果提供相同的数据，它应该与原始代码相同。
> 但是，要使我的代码工作，您必须了解原始项目的工作原理，因此我建议您先开始查看它，因为它更完整。

Thank you. I'll try again

**Comment by adore2005** [comment]
> 它使它们变得黑白分明，因为目标图纸是如此。如果提供相同的数据，它应该与原始代码相同。
> 但是，要使我的代码工作，您必须了解原始项目的工作原理，因此我建议您先开始查看它，因为它更完整。

Hello, I once put the three key frame pictures (renamed) that need to be filled in the "target" folder (deleted the pictures in the original folder) and deleted the pictures in the "output" folder. After running, the pictures in the original output folder are still obtained; Later, I tried to empty the pictures in the "target" folder and "output" folder, deleted the "00000. PNG", "00001. PNG" and "00002. PNG" pictures in the original "input" folder, and put the three key frame pictures (renamed) that need to be made up into the "input" folder. After running, the black-and-white key frame pictures are obtained; I'd like to ask you what i need to do if i want to use three key frame pictures to connect into animation? I want to use it for animation picture reference, but I'm not familiar with programming. I look forward to your answer.

**Comment by rnwzd** [comment]
Would you mind sharing the pictures with me as it is difficult to troubleshoot like this?
If you give me an email address I might be able to help you but this is not the place as it is not an issue with the repo.

Please mind that this is just a research project and it is very far from being a usable product for the end-user.

**Comment by adore2005** [comment]
> Would you mind sharing the pictures with me as it is difficult to troubleshoot like this?
> If you give me an email address I might be able to help you but this is not the place as it is not an issue with the repo.
> 
> Please mind that this is just a research project and it is very far from being a usable product for the end-user.

Of course, this is not a commercial picture, just a test. I want to make their transition pictures through these three pictures. Can you help me if you have time? My email: chu25636@163.com
![00002](https://user-images.githubusercontent.com/89287909/130378580-694fff77-5c90-4a48-8e9a-e839577d8972.png)
![00000](https://user-images.githubusercontent.com/89287909/130378583-8d04bad1-f7be-4a92-9e7f-0409bd7f7c93.png)
![00001](https://user-images.githubusercontent.com/89287909/130378585-b51eef1e-991d-4bb3-96c5-4dfcbd066488.png)

**Comment by rnwzd** [comment]
I am sorry but I am afraid that you have misunderstood the scope of the project:
the code is to translate a live-action video into a stylized video based on a reference translation.
It does not work to animate pictures that are not based on the live-action video.

You are looking for something different but I don't know anything that might be useful for your case.

**Comment by adore2005** [comment]
> 很抱歉，但我担心您误解了项目的范围：
> 代码是根据参考翻译将真人视频翻译成风格化视频。
> 不能为不是基于真人视频的图片制作动画。
> 
> 您正在寻找不同的东西，但我不知道任何可能对您的情况有用的东西。

Oh, I made a mistake. In addition, can this model achieve the transition of several key frame images？（ https://github.com/OndrejTexler/Few-Shot-Patch-Based-Training ）

**Comment by rnwzd** [comment]
No, that too needs reference video.

**Comment by adore2005** [comment]
> No, that too needs reference video.

In addition, I want to ask, if I use your model, can I make a transition for several static live-action key frame pictures?Or can i train with a series of transitional cartoon pictures, so that i can obtain a series of transitional cartoon pictures only through three cartoon key frame pictures？

**Comment by rnwzd** [comment]
You can look to the images I provided on Google drive:
You have a full video in folder input (e.g. 00001.png to 00050.png)
You have only a translation for some of the frames in the folder target (e.g. 00001.png)

The code tries to mimic the same translation for the remaining frames in input (from 00002.png to 00050.png)

The code is a translator, not an animator.

Again, everything is well explained in the original article.

**Comment by adore2005** [comment]
> 您可以查看我在 Google 驱动器上提供的图像：
> 您在文件夹输入中有完整的视频（例如 00001.png 到 00050.png）
> 您只有文件夹目标中某些帧的翻译（例如 00001.png）
> 
> 代码尝试模拟输入中剩余帧的相同转换（从 00002.png 到 00050.png）
> 
> 代码是翻译器，而不是动画师。
> 
> 同样，一切都在原始文章中得到了很好的解释。

That news may have misled me. It claims that there is a model that can generate continuous sequence frames from two key frame images.(https://blog.csdn.net/amusi1994/article/details/116467281)

**Comment by rnwzd** [comment]
Just two keyframes of drawings but based on all the keyframes of live-action.

Again, my project is just a partial reimplementation, if you want to know more, everything is explained in the original paper.

**Comment by adore2005** [comment]
> 只有两个关键帧的图纸，但基于所有真人动作的关键帧。
> 
> 同样，我的项目只是部分重新实现，如果您想了解更多，一切都在原始论文中进行了解释。

These media like to make false news. Also thank you for your answers.
